os: 
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
  - cmd: xmake --version

build_script:
  - cmd: xmake -y

