os: 
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/dev/scripts/get.ps1' -UseBasicParsing).Content
  - cmd: xmake --version

build_script:
  - cmd: xmake repo --add xmake-repo-dev https://github.com/tboox/xmake-repo.git dev
  - cmd: xmake -y -v

